// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywmhlfekgnjsfilqquwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3bWhsZmVrZ25qc2ZpbHFxdXd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMzQwMjEsImV4cCI6MjA2NjYxMDAyMX0.Sk4xV-8Pk7bJhwVLNyDa0qgD0tRc-aAN7eOpYMhUM2A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);